# Generated by Django 4.2.8 on 2025-05-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0086_alter_products_tech1"),
        ("payments", "0002_purchase_hosting_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="products",
            field=models.ManyToManyField(blank=True, to="common.products"),
        ),
    ]
