# Generated by Django 4.2.8 on 2024-05-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_file_article_video_alter_article_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_trusted_editor',
            field=models.BooleanField(default=False),
        ),
    ]
