# Generated by Django 4.2.8 on 2024-05-28 03:32

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_profile_is_trusted_editor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('WEBAPP', 'WebApp'), ('DASHBOARD', 'Dashboard'), ('API', 'Api')], default='WEBAPP', max_length=24)),
                ('info', models.CharField(default='', max_length=128)),
                ('features', django_quill.fields.QuillField()),
                ('documentation', django_quill.fields.QuillField()),
                ('seo_title', models.CharField(default='', max_length=128)),
                ('seo_tags', models.CharField(default='', max_length=128)),
                ('seo_description', models.CharField(default='', max_length=256)),
                ('canonical', models.CharField(default='', max_length=128)),
                ('code', models.CharField(max_length=128, unique=True)),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('free', models.BooleanField(default=True)),
                ('price', models.IntegerField(default=0)),
                ('price2', models.IntegerField(default=0)),
                ('pay_url', models.CharField(default=None, max_length=256)),
                ('pay_url2', models.CharField(default=None, max_length=256)),
                ('url_dw', models.CharField(default=None, max_length=256)),
                ('url_demo', models.CharField(default=None, max_length=256)),
                ('url_docs', models.CharField(default=None, max_length=256)),
                ('url_blog', models.CharField(default=None, max_length=256)),
                ('url_video', models.CharField(default=None, max_length=256)),
                ('url_changelog', models.CharField(default=None, max_length=256)),
                ('url_readme', models.CharField(default=None, max_length=256)),
                ('design', models.CharField(choices=[('NA', 'NA'), ('datta-able', 'datta-able'), ('datta-able-pro', 'datta-able-pro'), ('soft-ui-dashboard', 'soft-ui-dashboard'), ('soft-ui-dashboard-pro', 'soft-ui-dashboard-pro'), ('material-dashboard', 'material-dashboard'), ('material-dashboard-pro', 'material-dashboard-pro'), ('material-dashboard2-pro', 'material-dashboard2-pro'), ('argon-dashboard', 'material-dashboard'), ('argon-dashboard-pro', 'material-dashboard-pro'), ('argon-dashboard2-pro', 'material-dashboard2-pro')], default='NA', max_length=24)),
                ('design_by', models.CharField(choices=[('NA', 'NA'), ('creative-tim', 'creative-tim'), ('codedthemes', 'codedthemes'), ('themesberg', 'themesberg'), ('appseed', 'appseed')], default='NA', max_length=24)),
                ('design_system', models.CharField(choices=[('NA', 'NA'), ('soft-ui-design', 'soft-ui-design'), ('material-design', 'material-design'), ('argon-design', 'argon-design'), ('black-design', 'black-design'), ('flowbite', 'flowbite')], default='NA', max_length=24)),
                ('design_css', models.CharField(choices=[('NA', 'NA'), ('bootstrap', 'bootstrap'), ('bootstrap4', 'bootstrap4'), ('bootstrap5', 'bootstrap5'), ('tailwind', 'tailwind')], default='NA', max_length=24)),
                ('tech1', models.CharField(choices=[('NA', 'NA'), ('api-server', 'api-server'), ('django', 'django'), ('flask', 'flask'), ('nodejs', 'nodejs'), ('laravel', 'laravel'), ('nextjs', 'nextjs'), ('full-stack', 'full-stack')], default='NA', max_length=24)),
                ('tech2', models.CharField(choices=[('NA', 'NA'), ('react', 'react'), ('vuejs', 'vuejs'), ('nextjs', 'nextjs'), ('svelte', 'svelte')], default='NA', max_length=24)),
                ('tech3', models.CharField(choices=[('NA', 'NA'), ('react', 'react'), ('vuejs', 'vuejs'), ('nextjs', 'nextjs'), ('svelte', 'svelte')], default='NA', max_length=24)),
                ('tech4', models.CharField(default=None, max_length=64)),
                ('tech5', models.CharField(default=None, max_length=64)),
                ('downloads', models.IntegerField(default=0)),
            ],
        ),
    ]
