# Generated by Django 4.2.8 on 2024-05-28 08:04

import apps.common.models_products
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_products_created_at_products_updated_at'),
    ]

    operations = [
        
    ]
