# Generated by Django 4.2.8 on 2024-05-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_products_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='design',
            field=models.CharField(choices=[('NA', 'NA'), ('datta-able', 'datta-able'), ('datta-able-pro', 'datta-able-pro'), ('soft-ui-dashboard', 'soft-ui-dashboard'), ('soft-ui-dashboard-pro', 'soft-ui-dashboard-pro'), ('material-dashboard', 'material-dashboard'), ('material-dashboard-pro', 'material-dashboard-pro'), ('material-dashboard2-pro', 'material-dashboard2-pro'), ('argon-dashboard', 'argon-dashboard'), ('argon-dashboard-pro', 'argon-dashboard-pro'), ('argon-dashboard2-pro', 'argon-dashboard2-pro')], default='NA', max_length=24),
        ),
    ]
