# Generated by Django 4.2.8 on 2024-05-30 07:00

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_products_design'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PROGRAMMING', 'Programming'), ('FRAMEWORK', 'Framework'), ('DEPLOYMENT', 'Deployment'), ('NOCODE', 'No-Code')], max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='public_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='deployments',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category': 'DEPLOYMENT'}, related_name='deployments', to='common.skills'),
        ),
        migrations.AddField(
            model_name='profile',
            name='frameworks',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category': 'FRAMEWORK'}, related_name='frameworks', to='common.skills'),
        ),
        migrations.AddField(
            model_name='profile',
            name='no_codes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category': 'NOCODE'}, related_name='no_codes', to='common.skills'),
        ),
        migrations.AddField(
            model_name='profile',
            name='programming_languages',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category': 'PROGRAMMING'}, related_name='programming_languages', to='common.skills'),
        ),
    ]
