# Generated by Django 4.2.8 on 2024-05-30 08:54

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_skills_remove_profile_address_remove_profile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_type',
            field=models.CharField(blank=True, choices=[('DEVELOPER', 'Developer'), ('TEAMLEADER', 'Team Leader'), ('DESIGNER', 'Designer'), ('DEVOPS', 'DevOps'), ('ARCHITECT', 'Architect')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(limit_choices_to={'role': 'Company'}, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='common.profile')),
                ('members', models.ManyToManyField(blank=True, limit_choices_to={'role': 'User'}, related_name='members', to='common.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', django_quill.fields.QuillField(blank=True, null=True)),
                ('live_demo', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(limit_choices_to={'role': 'Company'}, on_delete=django.db.models.deletion.CASCADE, to='common.profile')),
                ('technologies', models.ManyToManyField(related_name='technologies', to='common.skills')),
            ],
        ),
    ]
