# Generated by Django 4.2.8 on 2024-05-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_profile_job_type_team_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'user'}, related_name='members', to='common.profile'),
        ),
    ]
