# Generated by Django 4.2.8 on 2024-06-02 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_teaminvitation_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.project'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TeamRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DEVELOPER', 'Developer'), ('TEAMLEADER', 'Team Leader'), ('DESIGNER', 'Designer'), ('DEVOPS', 'DevOps'), ('ARCHITECT', 'Architect')], max_length=255)),
                ('author', models.ForeignKey(limit_choices_to={'role': 'user'}, on_delete=django.db.models.deletion.CASCADE, related_name='team_role', to='common.profile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.team')),
            ],
        ),
    ]
