# Generated by Django 4.2.8 on 2024-06-02 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0014_teaminvitation_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('PRODUCT_ASSISTANCE', 'Product Assistance'), ('PLATFORM', 'Platform'), ('SUGGESTED_FEATURE', 'Suggested Feature')], default='PRODUCT_ASSISTANCE', max_length=100)),
                ('platform', models.CharField(blank=True, choices=[('PURCHASES', 'Purchases'), ('AUTHENTICATION', 'Authentication')], max_length=100, null=True)),
                ('states', models.CharField(choices=[('OPEN', 'Open'), ('ANSWERED', 'Answered'), ('CLOSED', 'Closed')], default='OPEN', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
