# Generated by Django 4.2.8 on 2024-06-02 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_profile_created_at_profile_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminvitation',
            name='member',
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.teamrole'),
        ),
    ]
