# Generated by Django 4.2.8 on 2024-06-02 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_alter_ticket_description_comment'),
        ('common', '0017_remove_teaminvitation_member_and_more'),
    ]

    operations = [
    ]
