# Generated by Django 4.2.8 on 2024-06-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_merge_20240602_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='job_type',
        ),
    ]
