# Generated by Django 4.2.8 on 2024-06-04 04:42

import apps.common.models_products
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_remove_profile_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='related_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_products', to='common.products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pay_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='pay_url2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.models_products.get_thumbnail_filename),
        ),
    ]
