# Generated by Django 4.2.8 on 2024-06-04 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_alter_article_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_trusted_editor',
            new_name='trusted',
        ),
    ]
