# Generated by Django 4.2.8 on 2024-06-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_alter_article_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_type',
            field=models.CharField(blank=True, choices=[('DEVELOPER', 'Developer'), ('TEAMLEADER', 'Team Leader'), ('DESIGNER', 'Designer'), ('DEVOPS', 'DevOps'), ('ARCHITECT', 'Architect')], max_length=20, null=True),
        ),
    ]
