# Generated by Django 4.2.8 on 2024-06-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_profile_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('HIGH', 'High')], default='LOW', max_length=50),
        ),
    ]
