# Generated by Django 4.2.8 on 2024-06-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_ticket_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='canonical_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
