# Generated by Django 4.2.8 on 2024-06-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_article_canonical_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('AUTHENTICATED_USER', 'Authenticated User'), ('PRO_USER', 'Pro User')], default='PUBLIC', max_length=30),
        ),
    ]
