# Generated by Django 4.2.8 on 2024-06-05 10:00

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_remove_team_project_project_team_team_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='features',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='tech4',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='tech5',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='url_blog',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='url_video',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
