# Generated by Django 4.2.8 on 2024-06-06 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_alter_products_features_alter_products_tech4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='created_at',
        ),
        migrations.AddField(
            model_name='products',
            name='release_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
