# Generated by Django 4.2.8 on 2024-06-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_remove_products_created_at_products_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
