# Generated by Django 4.2.8 on 2024-07-29 10:38

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0035_download_downloaded_release_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="products",
            name="tags",
            field=models.ManyToManyField(blank=True, to="common.producttag"),
        ),
    ]
