# Generated by Django 4.2.8 on 2024-07-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0036_producttag_products_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="products",
            name="url_video",
        ),
        migrations.AddField(
            model_name="products",
            name="videos",
            field=models.ManyToManyField(blank=True, to="common.productvideo"),
        ),
    ]
