# Generated by Django 4.2.8 on 2024-08-13 12:20

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0037_productvideo_remove_products_url_video_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="changelog",
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
