# Generated by Django 4.2.8 on 2024-08-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0038_products_changelog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="changelog",
            field=models.TextField(blank=True, null=True),
        ),
    ]
