# Generated by Django 4.2.8 on 2024-10-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0039_alter_products_changelog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="states",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("ANSWERED", "Answered"),
                    ("WORK_IN_PROGRESS", "Work in Progress"),
                    ("CLIENT_REPLY", "Client Reply"),
                    ("CLOSED", "Closed"),
                ],
                default="OPEN",
                max_length=50,
            ),
        ),
    ]
