# Generated by Django 4.2.8 on 2024-10-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0040_alter_ticket_states"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="design",
            field=models.CharField(
                choices=[
                    ("NA", "NA"),
                    ("datta-able", "datta-able"),
                    ("datta-able-pro", "datta-able-pro"),
                    ("gradient-able", "gradient-able"),
                    ("gradient-able-pro", "gradient-able-pro"),
                    ("berry-dashboard", "berry-dashboard"),
                    ("berry-dashboard-pro", "berry-dashboard-pro"),
                    ("volt-dashboard", "volt-dashboard"),
                    ("volt-dashboard-pro", "volt-dashboard-pro"),
                    ("soft-ui-dashboard", "soft-ui-dashboard"),
                    ("soft-ui-dashboard-pro", "soft-ui-dashboard-pro"),
                    ("material-dashboard", "material-dashboard"),
                    ("material-dashboard-pro", "material-dashboard-pro"),
                    ("material-dashboard2-pro", "material-dashboard2-pro"),
                    ("argon-dashboard", "argon-dashboard"),
                    ("argon-dashboard-pro", "argon-dashboard-pro"),
                    ("argon-dashboard2-pro", "argon-dashboard2-pro"),
                    ("black-dashboard", "black-dashboard"),
                    ("black-dashboard-pro", "black-dashboard-pro"),
                    ("adminlte", "adminlte"),
                    ("adminlte-pro", "adminlte-pro"),
                    ("coreui", "coreui"),
                    ("coreui-pro", "coreui-pro"),
                    ("material-kit", "material-kit"),
                    ("material-kit-pro", "material-kit-pro"),
                    ("argon-design", "argon-design"),
                    ("argon-design-pro", "argon-design-pro"),
                    ("pixel-bootstrap", "pixel-bootstrap"),
                    ("pixel-bootstrap-pro", "pixel-bootstrap-pro"),
                    ("soft-ui-design", "soft-ui-design"),
                    ("soft-ui-design-pro", "soft-ui-design-pro"),
                    ("bootstrap-design", "bootstrap-design"),
                    ("flowbite", "flowbite"),
                    ("tailwind", "tailwind"),
                    ("mui", "mui"),
                    ("shadcn", "shadcn"),
                    ("bulma", "bulma"),
                    ("pure-css", "pure-css"),
                ],
                default="NA",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="design_by",
            field=models.CharField(
                choices=[
                    ("NA", "NA"),
                    ("creative-tim", "creative-tim"),
                    ("codedthemes", "codedthemes"),
                    ("themesberg", "themesberg"),
                    ("appseed", "appseed"),
                    ("adminlte", "adminlte"),
                    ("coreui", "coreui"),
                    ("tailwind", "tailwind"),
                    ("flowbite", "flowbite"),
                    ("bootstrap", "bootstrap"),
                ],
                default="NA",
                max_length=24,
            ),
        ),
    ]
