# Generated by Django 4.2.8 on 2024-10-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0042_event_bookmark_updated_at_comment_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="text",
            field=models.CharField(max_length=512),
        ),
    ]
