# Generated by Django 4.2.8 on 2024-10-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0043_alter_event_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="tech1",
            field=models.CharField(
                choices=[
                    ("NA", "NA"),
                    ("api-server", "api-server"),
                    ("django", "django"),
                    ("flask", "flask"),
                    ("fast-api", "fast-api"),
                    ("nodejs", "nodejs"),
                    ("laravel", "laravel"),
                    ("nextjs", "nextjs"),
                    ("full-stack", "full-stack"),
                ],
                default="NA",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="tech2",
            field=models.CharField(
                choices=[
                    ("NA", "NA"),
                    ("react", "react"),
                    ("vuejs", "vuejs"),
                    ("svelte", "svelte"),
                ],
                default="NA",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="tech3",
            field=models.CharField(
                choices=[
                    ("NA", "NA"),
                    ("react", "react"),
                    ("vuejs", "vuejs"),
                    ("svelte", "svelte"),
                ],
                default="NA",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="type",
            field=models.CharField(
                choices=[
                    ("WEBAPP", "WebApp"),
                    ("DASHBOARD", "Dashboard"),
                    ("API", "Api"),
                ],
                default="DASHBOARD",
                max_length=24,
            ),
        ),
    ]
