# Generated by Django 4.2.8 on 2024-10-31 14:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0047_prompt"),
    ]

    operations = [
        migrations.CreateModel(
            name="Props",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                ("state", models.BooleanField(default=False)),
                ("data", models.CharField(max_length=255)),
                ("order", models.IntegerField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="common.products",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
