# Generated by Django 4.2.8 on 2024-10-31 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0049_article_featured"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomDevelopment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            (
                                "CUSTOM_SOFTWARE_DEVELOPMENT",
                                "Custom Software Development",
                            ),
                            ("SERVICE_OPTIMIZATION", "Service Optimization"),
                            ("CLOUDE_DEPLOYMENT", "Cloude Deployment"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "budget_range",
                    models.CharField(
                        choices=[
                            ("UNDER_5k", "Under $5000"),
                            ("F5K_T10k", "$5000 - $10,000"),
                            ("OVER_10k", "Over $10000"),
                        ],
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
