# Generated by Django 4.2.8 on 2024-11-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0050_customdevelopment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customdevelopment",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("CUSTOM_SOFTWARE_DEVELOPMENT", "Custom Software Development"),
                    ("SERVICE_OPTIMIZATION", "Service Optimization"),
                    (
                        "CLOUDE_DEPLOYMENT",
                        "Cloud Deployment (Digital Ocean, AWS, Azure)",
                    ),
                ],
                max_length=255,
            ),
        ),
    ]
