# Generated by Django 4.2.8 on 2024-11-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0051_alter_customdevelopment_project_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="user_id",
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
