# Generated by Django 4.2.8 on 2024-11-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0052_alter_prompt_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="videos",
        ),
    ]
