# Generated by Django 4.2.8 on 2024-11-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0056_alter_props_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="props",
            name="category",
            field=models.CharField(
                choices=[
                    ("DOWNLOAD", "Downlaod"),
                    ("FEATURE", "Feature"),
                    ("PROMO_NAME", "Promo Name"),
                    ("PROMO_COUPON", "Promo Coupon"),
                    ("PROMO_DISCOUNT", "Promo Discount"),
                    ("PROMO_INFO", "Promo Info"),
                ],
                max_length=250,
            ),
        ),
    ]
