# Generated by Django 4.2.8 on 2024-11-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0059_alter_props_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="info",
            field=models.CharField(default="", max_length=256),
        ),
    ]
