# Generated by Django 4.2.8 on 2024-11-07 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0062_remove_products_changelog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="documentation",
        ),
    ]
