# Generated by Django 4.2.8 on 2024-11-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0065_apikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="response",
            field=models.TextField(blank=True, null=True),
        ),
    ]
