# Generated by Django 4.2.8 on 2024-12-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0068_alter_event_type_alter_products_design"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="input",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="output",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
