# Generated by Django 4.2.8 on 2025-01-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0072_ticket_repo_url_alter_ticket_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedapp",
            name="task_log",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
