# Generated by Django 4.2.8 on 2025-01-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0073_alter_generatedapp_task_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedapp",
            name="api_key",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
