# Generated by Django 4.2.8 on 2025-03-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0076_alter_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedapp",
            name="backend",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="customdevelopment",
            name="budget_range",
            field=models.CharField(
                choices=[
                    ("UNDER_5k", "Under $5,000"),
                    ("F5K_T10k", "$5,000 - $10,000"),
                    ("OVER_10k", "Over $10,000"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="customdevelopment",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("CUSTOM_SOFTWARE_DEVELOPMENT", "Custom Development"),
                    ("TOOLS_RESEARCH", "DevTools & Research"),
                    ("DEPLOYMENT", "Deployment (Digital Ocean, AWS, Azure)"),
                ],
                max_length=255,
            ),
        ),
    ]
