# Generated by Django 4.2.8 on 2025-03-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0077_generatedapp_backend_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customdevelopment",
            name="budget_range",
            field=models.CharField(
                choices=[
                    ("UNDER_5k", "Small Change ~$1k"),
                    ("F5K_T10k", "Medium-size Projects ~$5k"),
                    ("OVER_10k", "Long-term Contracts > $25k"),
                ],
                max_length=100,
            ),
        ),
    ]
