# Generated by Django 4.2.8 on 2025-03-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0078_alter_customdevelopment_budget_range"),
    ]

    operations = [
        migrations.AddField(
            model_name="props",
            name="value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customdevelopment",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("CUSTOM_SOFTWARE_DEVELOPMENT", "Custom Development"),
                    ("TOOLS_RESEARCH", "DevTools"),
                    ("DEPLOYMENT", "Deployment (AWS, Azure, DO)"),
                    ("QA_AI_CODE", "AI/ML Generated Code Review"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="props",
            name="category",
            field=models.CharField(
                choices=[
                    ("DOWNLOAD", "Download"),
                    ("FEATURE", "Feature"),
                    ("PROMO_NAME", "Promo Name"),
                    ("PROMO_COUPON", "Promo Coupon"),
                    ("PROMO_DISCOUNT", "Promo Discount"),
                    ("PROMO_INFO", "Promo Info"),
                    ("PROMO_END_DATE", "Promo End Date"),
                    ("URL_VIDEO", "Video URL"),
                    ("URL_DOCS", "Docs URL"),
                    ("URL_BLOG", "Blog URL"),
                    ("LABEL", "LABEL"),
                ],
                max_length=250,
            ),
        ),
    ]
