# Generated by Django 4.2.8 on 2025-03-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0080_alter_event_created_at_alter_products_design"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
