# Generated by Django 4.2.8 on 2025-03-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0081_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
