# Generated by Django 4.2.8 on 2025-04-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0083_alter_products_design_alter_products_tech1_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={"ordering": ["name"]},
        ),
    ]
