# Generated by Django 4.2.8 on 2025-04-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0085_alter_products_tech1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="tech1",
            field=models.CharField(
                choices=[
                    ("NA", "NA"),
                    ("api-server", "api-server"),
                    ("django", "django"),
                    ("flask", "flask"),
                    ("fast-api", "fast-api"),
                    ("nodejs", "nodejs"),
                    ("laravel", "laravel"),
                    ("nextjs", "nextjs"),
                    ("nestjs", "nestjs"),
                    ("fullstack", "fullstack"),
                    ("firebase", "firebase"),
                    ("supabase", "supabase"),
                    ("streamlit", "streamlit"),
                    ("api-django", "api-django"),
                    ("api-flask", "api-flask"),
                    ("api-nodejs", "api-nodejs"),
                    ("api-nestjs", "api-nestjs"),
                ],
                default="NA",
                max_length=24,
            ),
        ),
    ]
