# Generated by Django 4.2.8 on 2025-05-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0086_alter_products_tech1"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="best_seller",
            field=models.BooleanField(default=False),
        ),
    ]
