# Generated by Django 4.2.8 on 2025-09-07 14:59

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0087_products_best_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="summary",
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
