# Generated by Django 4.2.8 on 2025-09-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0088_article_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="discounted",
            field=models.BooleanField(default=False),
        ),
    ]
